services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.5"
      MEMORY: "4G"

      ONLINE_MODE: "FALSE"
      SIMULATION_DISTANCE: 5
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        noisium
        c2me-fabric
        ferrite-core
        simple-voice-chat
        vanish
        anti-xray
        viafabric
      USES_PLUGINS: true

      MOTD: "&a&l&oAlmuerzo&r&3&o&oLand"

    volumes:
      - ./minecraft-data:/data

    restart: unless-stopped
